@startuml

title __DAO's Class Diagram__\n

  namespace dao {
    interface dao.ClientDAO {
        {abstract} + addNewClient()
        {abstract} + addNewRegion()
        {abstract} + deleteClient()
        {abstract} + deleteRegion()
        {abstract} + searchRegionByName()
        {abstract} + showAllClients()
        {abstract} + showAllRegions()
    }
  }
  

  namespace dao {
    interface dao.EmployerDAO {
        {abstract} + addNewEmployer()
        {abstract} + addNewPosition()
        {abstract} + deleteEmployer()
        {abstract} + deletePosition()
        {abstract} + searchPositionByName()
        {abstract} + showAllEmployers()
        {abstract} + showAllPosition()
    }
  }
  

  namespace dao {
    class dao.EmployerDAOImpl {
        + addNewEmployer()
        + addNewPosition()
        + deleteEmployer()
        + deletePosition()
        + searchPositionByName()
        + showAllEmployers()
        + showAllPosition()
    }
  }
  

  namespace dao {
    interface dao.IncidentDAO {
        {abstract} + showAllIncident()
        {abstract} + showAllProduct()
    }
  }
  

  namespace dao {
    class dao.IncidentDAOImpl {
        + showAllIncident()
        + showAllProduct()
    }
  }
  

  namespace dao {
    class dao.clientDAOImpl {
        + addNewClient()
        + addNewRegion()
        + deleteClient()
        + deleteRegion()
        + searchRegionByName()
        + showAllClients()
        + showAllRegions()
    }
  }
  

  dao.EmployerDAOImpl .up.|> dao.EmployerDAO
  dao.IncidentDAOImpl .up.|> dao.IncidentDAO
  dao.clientDAOImpl .up.|> dao.ClientDAO


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
